# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create!([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create!(name: 'Luke', movie: movies.first)
Category.create!(title: 'Programming languages')
Category.create!(title: 'Sign language')
User.create!(name: 'Andrew', gender: 'male')
User.create!(name: 'Viktoria', gender: 'female')
User.create!(name: 'Eugen', gender: 'male')
author = User.create!(name: 'Dmitriy', gender: 'male', admin: true)
Test.create!(title: 'Ruby_1p', level: 1, category_id: 1, author: author)
Test.create!(title: 'Ruby_2p', level: 2, category_id: 1,author: author)
Test.create!(title: 'HTML', level: 0, category_id: 1,author: author)
Test.create!(title: 'CSS', level: 2, category_id: 1, author: author)
Test.create!(title: 'Machine learning', level: 3, category_id: 1, author: author)
Question.create!(body: 'What language are you learning?', test_id: 1)
Question.create!(body: 'What language are you learning?', test_id: 2)
Question.create!(body: 'What language are you learning?', test_id: 3)
Question.create!(body: 'What language are you learning?', test_id: 4)
Answer.create!(body: 'English', correct: false, question_id: 1)
Answer.create!(body: 'France', correct: false, question_id: 1)
Answer.create!(body: 'Deutsch', correct: false, question_id: 1)
Answer.create!(body: 'Ruby', correct: true, question_id: 1)
Answer.create!(body: 'Japanese', correct: false, question_id: 2)
Answer.create!(body: 'Chinese', correct: false, question_id: 2)
Answer.create!(body: 'Kinyarwanda', correct: false, question_id: 2)
Answer.create!(body: 'HTML', correct: true, question_id: 2)
Answer.create!(body: 'Vietnamese', correct: false, question_id: 3)
Answer.create!(body: 'Korean', correct: false, question_id: 3)
Answer.create!(body: 'Georgian', correct: false, question_id: 3)
Answer.create!(body: 'CSS', correct: true, question_id: 3)
Answer.create!(body: 'Portuguese', correct: false, question_id: 4)
Answer.create!(body: 'Spanish', correct: false, question_id: 4)
Answer.create!(body: 'Uzbek', correct: false, question_id: 4)
Answer.create!(body: 'Machine learning', correct: true, question_id: 4)